config/routes.rb
BugTracker::Application.routes.draw do
  resources :bugs
  resources :site_settings

  root 'bugs#index'

  

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  after_initialize :init

  def init
    self.state ||= 0
  end
end

app/models/site_settings.rb
class SiteSettings < RailsSettings::CachedSettings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == SiteSettings.admin_name && password == SiteSettings.password
    end
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => :create
  before_filter :authenticate_user, :only => :create
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }


  # GET /bugs
  # GET /bugs.json
  def index
    if request.format == 'application/json'
      @bugs = Bug.order(:created_at).order(:state).limit(params[:limit]).all
    else
      @bugs = Bug.order(:created_at).order(:state).paginate(:page => params[:page], :per_page => 50)
    end
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bug }
      else
        format.html { render action: 'new' }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url }
      format.json { head :no_content }
    end
  end

  private
  def authenticate_user
    authenticate_or_request_with_http_basic do |username, password|
      username == SiteSettings.user_name && password == SiteSettings.user_password
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bug
    @bug = Bug.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bug_params
    params.require(:bug).permit(:description, :contact, :version, :state)
  end

  def get_name_from_settings
    logger.debug "Name is: #{SiteSettings.admin_name}"
    logger.debug "Password is: #{SiteSettings.password}"
  end
end

app/controllers/site_settings_controller.rb
class SiteSettingsController < ApplicationController
  before_action :set_setting, only: [:update]
  before_filter :authenticate

  def index
    # to get all items for render list
    @settings = SiteSettings.unscoped
  end

  def update
    respond_to do |format|
      SiteSettings[params[:id]] = setting_params[:value]
      logger.debug setting_params[:value]
      format.html { redirect_to site_settings_path, notice: 'Settings was successfully updated.' }
      format.json { head :no_content }
    end
  end

  private

  def set_setting

  end

  def setting_params
    params.require(:site_settings).permit(:value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
  def get_state_name(state_number)
    case state_number
      when 0 then
        'New'
      when 1 then
        'Investigating'
      when 2 then
        'Performing bug fix'
      when 3 then
        'Unconfirmed'
      when 4 then
        'Will not be fixed'
      when 5 then
        'Fixed'
      else
        'Unidentified'
    end

  end
end

app/views/bugs/_form.html.erb
<%= form_for(@bug) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1>Editing bug</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/index.html.erb
<h1>Listing bugs</h1>

<table>
  <thead>
  <tr>
    <th>Description</th>
    <th>Contact</th>
    <th>Version</th>
    <th>State</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @bugs.each do |bug| %>
      <tr>
        <td><%= link_to bug.description.truncate(64), bug %></td>
        <td><%= bug.contact %></td>
        <td><%= bug.version %></td>
        <td><%= get_state_name(bug.state) %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= page_entries_info @bugs %>
<%= will_paginate @bugs %>

<br>
<br>
<%= link_to 'New Bug', new_bug_path %>

app/views/bugs/new.html.erb
<h1>New bug</h1>

<%= render 'form' %>

<%= link_to 'Back', bugs_path %>

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @bug.description %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @bug.contact %>
</p>

<p>
  <strong>State:</strong>
  <%= get_state_name(@bug.state) %>
</p>

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BugTracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site_settings/index.html.erb
<h1>Listing site settings</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @settings.each do |setting| %>
      <%= form_for(setting, :url => site_setting_url(setting.var)) do |f| %>
          <tr>
            <td><%= setting.var %></td>
            <td><%= f.text_field :value %></td>
            <td><%= f.submit %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>